INSERT INTO mRoom VALUES (1, 30);
INSERT INTO mRoom VALUES (2, 30);
INSERT INTO mRoom VALUES (3, 30);
INSERT INTO mRoom VALUES (4, 26);
INSERT INTO mRoom VALUES (5, 26);
INSERT INTO mRoom VALUES (6, 26);
select * from mRoom;