--교재 더미

INSERT INTO mBook VALUES (1, '자바의 정석', '도우출판');
INSERT INTO mBook VALUES (2, '처음 배우는 NHN Cloud', '한빛미디어');
INSERT INTO mBook VALUES (3, '이것이 리눅스다 with Rocky Linux9', '한빛미디어');
INSERT INTO mBook VALUES (4, 'Figma 가이드북', '비제이퍼블릭');
INSERT INTO mBook VALUES (5, 'Android Studio를 활용한 안드로이드 프로그래밍', '한빛아카데미');
INSERT INTO mBook VALUES (6, 'Firebase로 안드로이드 SNS 앱 만들기', '비제이퍼블릭');
INSERT INTO mBook VALUES (7, '오라클로 배우는 데이터베이스 개론과 실습', '한빛아카데미');
INSERT INTO mBook VALUES (8, 'HTML 5 웹 프로그래밍 입문', '생능');
INSERT INTO mBook VALUES (9, 'Do it! 점프 투 파이썬', '이지스퍼블리싱');
INSERT INTO mBook VALUES (10, '빅데이터 개론', '광문각');
INSERT INTO mBook VALUES (11, 'MySQL로 배우는 데이터베이스 개론과 실습', '한빛아카데미');
INSERT INTO mBook VALUES (12, '킹 오브 네트워킹', '네버스탑');
INSERT INTO mBook VALUES (13, '프로그래밍 루비', '인사이트');
INSERT INTO mBook VALUES (14, '그림과 작동 원리로 쉽게 이해하는 AWS 구조와 서비스', '위키북스');
INSERT INTO mBook VALUES (15, '모던 자바스크립트 Deep Dive', '위키북스');
INSERT INTO mBook VALUES (16, '이것이 C#이다', '한빛미디어');
INSERT INTO mBook VALUES (17, 'PHP 프로그래밍', '21세기사');
INSERT INTO mBook VALUES (18, 'Go 언어 시작하기', '홍릉');
INSERT INTO mBook VALUES (19, 'D 프로그래밍언어', '대웅');
INSERT INTO mBook VALUES (20, '컴퓨터 비전과 딥러닝', '한빛아카데미');
INSERT INTO mBook VALUES (21, '파이썬 프로그래밍', '한빛아카데미');
INSERT INTO mBook VALUES (22, 'React Native로 모바일 앱 만들기', '한빛미디어');
INSERT INTO mBook VALUES (23, 'Node.js 완벽 가이드', '위키북스');
INSERT INTO mBook VALUES (24, 'Angular 시작하기', '비제이퍼블릭');
INSERT INTO mBook VALUES (25, 'Spring Boot 완벽 가이드', '한빛미디어');
INSERT INTO mBook VALUES (26, 'JavaScript 심화', '위키북스');
INSERT INTO mBook VALUES (27, 'PHP 기초부터 실무까지', '21세기사');
INSERT INTO mBook VALUES (28, 'MySQL 심화', '한빛아카데미');
INSERT INTO mBook VALUES (29, '기초부터 배우는 머신러닝', '광문각');
INSERT INTO mBook VALUES (30, '빅데이터 분석', '한빛아카데미');
INSERT INTO mBook VALUES (31, '인공지능 기초', '한빛미디어');
INSERT INTO mBook VALUES (32, '딥러닝 모델', '생능');
INSERT INTO mBook VALUES (33, '모던 자바스크립트', '위키북스');
INSERT INTO mBook VALUES (34, 'Go 언어 실전', '홍릉');
INSERT INTO mBook VALUES (35, 'C++ 프로그래밍 입문', '대웅');
INSERT INTO mBook VALUES (36, 'Kotlin 프로그래밍', '비제이퍼블릭');
INSERT INTO mBook VALUES (37, 'UI/UX 디자인 완벽 가이드', '한빛미디어');
INSERT INTO mBook VALUES (38, 'AWS 실전', '위키북스');
INSERT INTO mBook VALUES (39, 'Docker와 Kubernetes', '한빛아카데미');
INSERT INTO mBook VALUES (40, '게임 개발의 이론과 실습', '광문각');
INSERT INTO mBook VALUES (41, '데이터베이스 설계', '생능');
INSERT INTO mBook VALUES (42, 'C# 프로그래밍', '한빛미디어');
INSERT INTO mBook VALUES (43, '컴퓨터 비전', '한빛아카데미');
INSERT INTO mBook VALUES (44, '리눅스 시스템 관리', '한빛미디어');
INSERT INTO mBook VALUES (45, '데이터 분석 기초', '위키북스');
INSERT INTO mBook VALUES (46, 'Java 프로그래밍 실전', '21세기사');
INSERT INTO mBook VALUES (47, 'Python 데이터 분석', '한빛미디어');
INSERT INTO mBook VALUES (48, 'Java 웹 프로그래밍', '위키북스');
INSERT INTO mBook VALUES (49, '기계학습과 AI', '한빛아카데미');
INSERT INTO mBook VALUES (50, '컴퓨터 네트워크', '한빛미디어');

select * FROM MBOOK;