INSERT INTO mAdminTeacherEval VALUES (1, 5, TO_DATE('2024-04-20', 'YYYY-MM-DD'), '결석 없이 매 수업에 참석하시며, 항상 수업을 빠짐없이 진행하십니다.', 1, 1);
INSERT INTO mAdminTeacherEval VALUES (2, 5, TO_DATE('2024-04-20', 'YYYY-MM-DD'), '강사님은 수업의 시간 배분이 잘 되어 있어, 학생들이 지루하지 않도록 잘 관리하십니다.', 2, 1);
INSERT INTO mAdminTeacherEval VALUES (3, 5, TO_DATE('2024-07-20', 'YYYY-MM-DD'), '수업을 시작하기 전에 항상 강의 계획서를 학생들에게 미리 제공하여 준비할 수 있게 해주십니다.', 1, 2);
INSERT INTO mAdminTeacherEval VALUES (4, 5, TO_DATE('2024-07-20', 'YYYY-MM-DD'), '강사님은 수업 시작 전에 항상 자료를 확인하고 준비해주셔서 학생들이 수업에 집중할 수 있도록 도와줍니다.', 2, 2);
INSERT INTO mAdminTeacherEval VALUES (5, 5, TO_DATE('2024-10-10', 'YYYY-MM-DD'), '수업이 끝난 후에도 학생들에게 필요한 자료를 제공하고, 학습에 대한 피드백을 철저히 제공합니다.', 1, 3);
INSERT INTO mAdminTeacherEval VALUES (6, 5, TO_DATE('2024-12-10', 'YYYY-MM-DD'), '강사님의 근태가 매우 좋으며, 매번 수업을 철저하게 준비하여 진행해주십니다.', 1, 4);
INSERT INTO mAdminTeacherEval VALUES (7, 5, TO_DATE('2024-12-02', 'YYYY-MM-DD'), '실습 시간이 충분히 주어져서 학생들이 이론을 실습을 통해 확실히 이해할 수 있었습니다.', 1, 5);
INSERT INTO mAdminTeacherEval VALUES (8, 5, TO_DATE('2024-10-05', 'YYYY-MM-DD'), '수업 내용을 체계적으로 정리해주셔서 학생들이 이해하기 쉬웠습니다.', 1, 6);
INSERT INTO mAdminTeacherEval VALUES (9, 5, TO_DATE('2024-12-10', 'YYYY-MM-DD'), '수업 중 학생들에게 친근하게 다가가며, 학습 분위기를 잘 이끌어갑니다.', 2, 4);
INSERT INTO mAdminTeacherEval VALUES (10, 5, TO_DATE('2024-03-20', 'YYYY-MM-DD'), '학생들의 동기부여를 잘 해주시며, 수업을 재미있게 만드십니다.', 1, 7);
INSERT INTO mAdminTeacherEval VALUES (11, 4, TO_DATE('2024-04-20', 'YYYY-MM-DD'), '항상 학생들에게 긍정적인 피드백을 주어 자신감을 갖게 만듭니다.', 3, 1);
INSERT INTO mAdminTeacherEval VALUES (12, 4, TO_DATE('2024-04-20', 'YYYY-MM-DD'), '강사님은 수업 자료를 잘 준비해주셔서, 학생들이 수업을 만족스러워했습니다.', 4, 1);
INSERT INTO mAdminTeacherEval VALUES (13, 4, TO_DATE('2024-03-20', 'YYYY-MM-DD'), '수업이 매우 실용적이어서, 학생들이 실제 현업에서 사용할 수 있는 지식과 기술을 배웠습니다.', 2, 7);
INSERT INTO mAdminTeacherEval VALUES (14, 4, TO_DATE('2024-03-20', 'YYYY-MM-DD'), '강사님은 수업 시간 외에도 학습에 도움이 될 만한 자료를 준비해주셨습니다.', 3, 7);
INSERT INTO mAdminTeacherEval VALUES (15, 4, TO_DATE('2024-02-20', 'YYYY-MM-DD'), '학생들에게 예시를 들어가며 수업을 진행해주셔서 한명의 낙오자도 발생하지 않았습니다.', 1, 8);
INSERT INTO mAdminTeacherEval VALUES (16, 4, TO_DATE('2024-12-10', 'YYYY-MM-DD'), '강사님은 항상 수업 후에도 질문을 받아주시고, 개별적인 피드백을 잘 해주십니다.', 3, 4);
INSERT INTO mAdminTeacherEval VALUES (17, 4, TO_DATE('2024-07-20', 'YYYY-MM-DD'), '학생들이 수업을 잘 따라올 수 있도록 각 파트를 차근차근 진행해주십니다.', 3, 2);
INSERT INTO mAdminTeacherEval VALUES (18, 4, TO_DATE('2024-12-10', 'YYYY-MM-DD'), '강사님은 항상 열정적이며, 수업에 대한 준비가 철저합니다.', 4, 4);
INSERT INTO mAdminTeacherEval VALUES (19, 4, TO_DATE('2024-10-10', 'YYYY-MM-DD'), '강사님은 다양한 학습 자료를 활용해 준비를 철저히하십니다.', 2, 3);
INSERT INTO mAdminTeacherEval VALUES (20, 4, TO_DATE('2024-10-05', 'YYYY-MM-DD'), '학생들에게 필요한 피드백을 즉각적으로 주시고, 개선할 수 있는 점을 정확히 알려주십니다.', 2, 6);
INSERT INTO mAdminTeacherEval VALUES (21, 3, TO_DATE('2024-10-05', 'YYYY-MM-DD'), '강사님은 대체로 친절하셨지만, 수업 진행 중에 다른 학생들에게 너무 많은 시간을 할애하시고 일부 학생들이 소외되었던 것 같습니다.', 3, 6);
INSERT INTO mAdminTeacherEval VALUES (22, 3, TO_DATE('2024-12-10', 'YYYY-MM-DD'), '수업 내용은 괜찮았으나, 가끔씩 예시가 부족해 수업을 이해하는 데 어려운 부분이 있다는 컴플레인을 받았습니다.', 5, 4);
INSERT INTO mAdminTeacherEval VALUES (23, 3, TO_DATE('2024-07-20', 'YYYY-MM-DD'), '강사님은 수업 준비가 어느 정도 되어 있었지만, 수업 후에 피드백이 조금 부족하여 학생들이 개선할 부분을 명확히 알지 못한 경우가 있었습니다.', 4, 2);
INSERT INTO mAdminTeacherEval VALUES (24, 3, TO_DATE('2024-10-10', 'YYYY-MM-DD'), '수업은 잘 진행되었으나, 학생들의 개별적인 이해도를 체크하는 시간이 부족했던 것 같습니다.', 3, 3);
INSERT INTO mAdminTeacherEval VALUES (25, 3, TO_DATE('2024-02-20', 'YYYY-MM-DD'), '강사님은 성실히 수업을 진행하셨지만, 수업이 조금 길어져 학생들이 집중력을 유지하는 데 어려움을 겪었던 것 같습니다.', 2, 8);
INSERT INTO mAdminTeacherEval VALUES (26, 3, TO_DATE('2024-02-20', 'YYYY-MM-DD'), '강사님은 수업을 진행할 때 좋은 분위기를 조성하셨지만, 학생들이 추가적인 질문을 하는 데 조금 더 열린 자세를 보여주시면 좋겠습니다.', 3, 8);
INSERT INTO mAdminTeacherEval VALUES (27, 3, TO_DATE('2024-04-20', 'YYYY-MM-DD'), '강사님의 수업은 체계적이었지만, 때때로 수업의 중요한 부분이 너무 빠르게 지나갔던 것 같아 학생들이 따라가기 어려웠을 수 있습니다.', 5, 1);
INSERT INTO mAdminTeacherEval VALUES (28, 3, TO_DATE('2024-02-20', 'YYYY-MM-DD'), '학생들의 수준에 맞춰 수업의 난이도를 조금 더 조정하시면 좋을 것 같습니다.', 4, 8);
INSERT INTO mAdminTeacherEval VALUES (29, 2, TO_DATE('2024-12-02', 'YYYY-MM-DD'), '강사님은 수업을 진행하는 데 어려움은 없으셨지만, 학생들이 충분히 이해할 때까지 반복적으로 설명해주셨으면 더 좋았을 것 같습니다.', 2, 5);
INSERT INTO mAdminTeacherEval VALUES (30, 2, TO_DATE('2024-02-20', 'YYYY-MM-DD'), '강사님은 지각은 하지 않았지만, 때때로 수업 내용에 대한 준비가 부족하여 수업이 산만했습니다.', 5, 8);
INSERT INTO mAdminTeacherEval VALUES (31, 2, TO_DATE('2024-12-02', 'YYYY-MM-DD'), '너무 많은 과제를 내주셔서 학생들이 과중한 부담을 느꼈습니다.', 3, 5);
INSERT INTO mAdminTeacherEval VALUES (32, 2, TO_DATE('2024-03-20', 'YYYY-MM-DD'), '강사님은 수업을 진행할 때 때때로 내용이 너무 빨리 진행되어 따라가기가 어렵다고 들었습니다.', 4, 7);
INSERT INTO mAdminTeacherEval VALUES (33, 1, TO_DATE('2024-03-20', 'YYYY-MM-DD'), '수업에 지각하는 일이 자주 발생하여, 학생들이 불편함을 느꼈습니다.', 5, 7);
INSERT INTO mAdminTeacherEval VALUES (34, 1, TO_DATE('2024-10-10', 'YYYY-MM-DD'), '수업 준비가 항상 부족하고, 강사님의 지각으로 수업의 질이 떨어졌습니다.', 4, 3);
INSERT INTO mAdminTeacherEval VALUES (35, 1, TO_DATE('2024-07-20', 'YYYY-MM-DD'), '수업 중에 강사님이 자주 자리를 비우셔서 학생들이 집중하기 어려웠습니다.', 5, 2);
INSERT INTO mAdminTeacherEval VALUES (36, 1, TO_DATE('2024-10-05', 'YYYY-MM-DD'), '강사님의 수업은 준비가 미비하여 수업이 진행되는 동안 학생들이 이해하기 어려웠습니다.', 4, 6);
INSERT INTO mAdminTeacherEval VALUES (37, 1, TO_DATE('2024-10-05', 'YYYY-MM-DD'), '강사님의 수업 준비가 부족하여, 수업 시작 전 항상 긴급히 자료를 준비하는 상황이 발생했습니다.', 5, 6);
INSERT INTO mAdminTeacherEval VALUES (38, 1, TO_DATE('2024-10-10', 'YYYY-MM-DD'), '강사님의 지각이 잦아 수업이 중단되는 일이 발생해 학생들이 불편함을 겪었습니다.', 5, 3);
INSERT INTO mAdminTeacherEval VALUES (39, 1, TO_DATE('2024-12-02', 'YYYY-MM-DD'), '강사님은 결석이 많아, 수업을 대신할 대체 강사가 필요할 때가 많았습니다.', 4, 5);
INSERT INTO mAdminTeacherEval VALUES (40, 1, TO_DATE('2024-12-02', 'YYYY-MM-DD'), '수업이 진행되는 동안 강사님은 너무 자주 자리를 비우셔서 학생들이 불편해 했습니다.', 5, 5);
INSERT INTO mAdminTeacherEval VALUES (41, 5, TO_DATE('2024-01-20', 'YYYY-MM-DD'), '각 학생의 수준을 파악하고 맞춤형 피드백을 주셔서, 학생들이 더욱 발전할 수 있도록 도와주셨습니다.', 1, 9);
INSERT INTO mAdminTeacherEval VALUES (42, 5, TO_DATE('2024-01-20', 'YYYY-MM-DD'), '수업 준비가 철저하고, 실습을 통해 이론을 쉽게 이해할 수 있도록 도와주셨습니다. 학생들에게 큰 도움이 되었습니다.', 2, 9);
INSERT INTO mAdminTeacherEval VALUES (43, 5, TO_DATE('2024-01-20', 'YYYY-MM-DD'), '적극적으로 수업을 이끌어가시며, 수업 외 시간에도 학생들에게 필요한 추가적인 설명을 해주셨습니다.', 3, 9);
INSERT INTO mAdminTeacherEval VALUES (44, 4, TO_DATE('2024-01-20', 'YYYY-MM-DD'), '강사님은 수업의 각 파트를 명확하게 정리하시고, 학생들이 학습할 수 있도록 환경을 잘 조성해주셨습니다.', 4, 9);
INSERT INTO mAdminTeacherEval VALUES (45, 4, TO_DATE('2024-01-20', 'YYYY-MM-DD'), '지각 없이 매 수업을 진행하시며, 항상 정시 시작하여 학생들에게 좋은 본보기가 되셨습니다.', 5, 9);
INSERT INTO mAdminTeacherEval VALUES (46, 5, TO_DATE('2024-01-27', 'YYYY-MM-DD'), '강사님은 매 수업마다 철저히 준비하시고, 학생들의 수준에 맞춘 설명이 뛰어났습니다.', 1, 10);
INSERT INTO mAdminTeacherEval VALUES (47, 5, TO_DATE('2024-01-27', 'YYYY-MM-DD'), '학생들이 수업에 적극적으로 참여하도록 유도하시고, 피드백도 매우 구체적이고 도움이 되었습니다.', 2, 10);
INSERT INTO mAdminTeacherEval VALUES (48, 5, TO_DATE('2024-01-27', 'YYYY-MM-DD'), '강사님은 항상 학생들의 질문에 신속하고 정확하게 답변해주시며, 학생들의 이해를 돕기 위해 다양한 예시를 들어주셨습니다.', 3, 10);
INSERT INTO mAdminTeacherEval VALUES (49, 5, TO_DATE('2024-01-27', 'YYYY-MM-DD'), '수업 진행 속도와 내용에 있어 매우 적절하게 균형을 맞추셔서 모든 학생들이 이해할 수 있게 배려하셨습니다.', 4, 10);
INSERT INTO mAdminTeacherEval VALUES (50, 4, TO_DATE('2024-01-27', 'YYYY-MM-DD'), '수업을 매우 열정적으로 진행하셨고, 학생들을 잘 챙기셨습니다.', 5, 10);


select * from mAdminTeacherEval;