-- 자료
INSERT INTO mMaterial VALUES (1, 'AWS 공식 문서', 'https://docs.aws.amazon.com', 'AWS 서비스 및 활용법 공식 문서', 1, 1, '2024-12-05');
INSERT INTO mMaterial VALUES (2, 'AWS Certified Solutions Architect Study Guide', 'https://www.oreilly.com/library/view/aws-certified-solutions/9781119504214/', 'AWS 인증 시험 준비용 참고서', 5, 9, '2024-03-10');
INSERT INTO mMaterial VALUES (3, 'Amazon Web Services in Action', 'https://www.manning.com/books/amazon-web-services-in-action', 'AWS 기초부터 고급까지 실습 중심 설명', 1, 1, '2024-12-21');
INSERT INTO mMaterial VALUES (4, 'AWS 무료 티어 실습', 'https://aws.amazon.com/free/', 'AWS의 무료 티어를 활용한 실습 가이드', 5, 9, '2024-03-10');
INSERT INTO mMaterial VALUES (5, 'AWS Well-Architected Framework', 'https://docs.aws.amazon.com/wellarchitected/latest/framework/', 'AWS 아키텍처 설계 원칙 및 베스트 프랙티스', 1, 1, '2024-12-15');
INSERT INTO mMaterial VALUES (6, 'AWS Lambda 활용', 'https://aws.amazon.com/lambda/', '서버리스 컴퓨팅 개념 및 실습', 5, 9, '2024-03-10');
INSERT INTO mMaterial VALUES (7, 'AWS Certified Developer Guide', 'https://www.amazon.com/dp/1119508202', 'AWS 개발자 인증 시험 준비용', 1, 1, '2024-12-10');
INSERT INTO mMaterial VALUES (8, 'AWS Hands-on Labs', 'https://qwiklabs.com/', 'AWS 실습 및 퀘스트 제공 사이트', 5, 9, '2024-03-10');
INSERT INTO mMaterial VALUES (9, 'AWS 클라우드 네트워크 설계', 'https://acloudguru.com/', 'AWS 기반 네트워크 설계 및 최적화 가이드', 1, 1, '2024-12-06');
INSERT INTO mMaterial VALUES (10, 'AWS 공식 유튜브', 'https://www.youtube.com/c/AmazonWebServices', 'AWS 관련 최신 기술과 웨비나 제공', 1, 1, '2024-01-01');
INSERT INTO mMaterial VALUES (11, 'Frontend Masters', 'https://frontendmasters.com/', '클라이언트 개발을 위한 고급 프론트엔드 강의 제공', 1, 1, '2024-12-05');
INSERT INTO mMaterial VALUES (12, 'MDN Web Docs', 'https://developer.mozilla.org/', 'HTML, CSS, JavaScript의 공식 문서', 1, 1, '2024-12-05');
INSERT INTO mMaterial VALUES (13, 'Eloquent JavaScript', 'https://eloquentjavascript.net/', '자바스크립트 개념과 코드 예제 학습', 1, 1, '2024-12-05');
INSERT INTO mMaterial VALUES (14, 'You Don’t Know JS', 'https://github.com/getify/You-Dont-Know-JS', '자바스크립트 심화 개념 학습', 1, 1, '2024-12-05');
INSERT INTO mMaterial VALUES (15, 'Spring 공식 문서', 'https://spring.io/projects/spring-framework', 'Spring 프레임워크 공식 문서 및 가이드', 1, 1, '2024-12-05');
INSERT INTO mMaterial VALUES (16, 'Spring Boot in Action', 'https://www.manning.com/books/spring-boot-in-action', 'Spring Boot 학습을 위한 실습 가이드', 1, 1, '2024-12-05');
INSERT INTO mMaterial VALUES (17, 'Spring 데이터 JPA', 'https://spring.io/projects/spring-data-jpa', 'Spring을 활용한 JPA 데이터 관리 개념', 1, 1, '2024-12-05');
INSERT INTO mMaterial VALUES (18, '클라우드 컴퓨팅 개념', 'https://www.ibm.com/cloud/learn/cloud-computing', '클라우드 컴퓨팅 개념 및 활용법', 5, 9, '2024-03-10');
INSERT INTO mMaterial VALUES (19, 'Cloud Native Computing Foundation', 'https://www.cncf.io/', '클라우드 네이티브 기술과 오픈소스 프로젝트 소개', 5, 9, '2024-03-10');
INSERT INTO mMaterial VALUES (20, 'Kubernetes 공식 문서', 'https://kubernetes.io/docs/', '컨테이너 오케스트레이션 시스템 Kubernetes 공식 가이드', 5, 9, '2024-03-10');
INSERT INTO mMaterial VALUES (21, '클라우드 보안 베스트 프랙티스', 'https://cloudsecurityalliance.org/', '클라우드 환경에서 보안 강화를 위한 권장 사항', 5, 9, '2024-03-10');
INSERT INTO mMaterial VALUES (22, '빅데이터 개념', 'https://www.ibm.com/cloud/learn/big-data', '빅데이터 개념 및 활용법', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (23, 'Hadoop 공식 문서', 'https://hadoop.apache.org/docs/', 'Hadoop 분산 데이터 처리 프레임워크', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (24, 'Spark 공식 문서', 'https://spark.apache.org/docs/latest/', 'Apache Spark를 활용한 데이터 분석 가이드', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (25, '데이터 시각화 개념', 'https://www.tableau.com/learn/articles/data-visualization', '데이터 시각화의 중요성과 기법 소개', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (26, 'SQL for Data Science', 'https://www.coursera.org/learn/sql-for-data-science', '데이터 과학을 위한 SQL 활용법', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (27, 'R을 이용한 빅데이터 분석', 'https://www.datacamp.com/courses/r-for-big-data', 'R 프로그래밍을 통한 빅데이터 분석 기법', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (28, '데이터구조 개요', 'https://www.geeksforgeeks.org/data-structures/', '데이터구조의 기본 개념과 중요성', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (29, '배열의 사용법', 'https://www.geeksforgeeks.org/arrays-in-c-cpp/', '배열을 사용한 데이터 저장 및 검색', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (30, '연결 리스트', 'https://www.geeksforgeeks.org/data-structures/linked-list/', '연결 리스트의 개념 및 구현', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (31, '스택과 큐', 'https://www.geeksforgeeks.org/stack-data-structure/', '스택과 큐의 개념과 활용', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (32, '트리와 이진 트리', 'https://www.geeksforgeeks.org/binary-tree-data-structure/', '트리 자료구조 및 이진 트리의 사용법', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (33, '블록체인 기술 개요', 'https://www.ibm.com/topics/what-is-blockchain', '블록체인 기술의 정의와 활용', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (34, '블록체인 보안', 'https://www.csoonline.com/article/3332347/what-is-blockchain-security.html', '블록체인의 보안 원리와 기법', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (35, '이더리움 기초', 'https://ethereum.org/en/developers/docs/', '이더리움 블록체인 및 스마트 계약', 2, 2, '2024-01-06');
INSERT INTO mMaterial VALUES (36, '자바 프로그래밍 기초', 'https://www.oracle.com/java/technologies/javase-jdk11-downloads.html', '자바 기초 문법 및 설치법', 3, 3, '2024-01-22');
INSERT INTO mMaterial VALUES (37, '자바 메모리 관리', 'https://www.baeldung.com/java/java-memory-management', '자바에서의 메모리 관리 기법', 8, 12, '2024-01-31');
INSERT INTO mMaterial VALUES (38, '자바 객체지향 프로그래밍', 'https://www.tutorialspoint.com/java/java_object_oriented.htm', '자바에서 객체지향 프로그래밍 개념', 8, 12, '2024-01-31');
INSERT INTO mMaterial VALUES (39, '자바 네트워크 프로그래밍', 'https://docs.oracle.com/javase/tutorial/networking/', '자바에서의 네트워크 프로그래밍 기법', 3, 3, '2024-01-22');
INSERT INTO mMaterial VALUES (40, '자바 멀티스레딩', 'https://www.geeksforgeeks.org/multithreading-in-java/', '자바에서 멀티스레딩 구현법', 8, 12, '2024-01-31');
INSERT INTO mMaterial VALUES (41, '자바 파일 입출력 처리', 'https://docs.oracle.com/javase/tutorial/essential/io/', '파일 입출력과 데이터 처리 기법', 8, 12, '2024-01-31');
INSERT INTO mMaterial VALUES (42, '자바 람다 표현식', 'https://www.baeldung.com/java/lambda-expressions', '자바에서 람다 표현식의 활용', 3, 3, '2024-01-22');
INSERT INTO mMaterial VALUES (43, '자바 8 새로운 기능', 'https://www.geeksforgeeks.org/java-8-features/', '자바 8에서의 주요 기능', 8, 12, '2024-01-31');
INSERT INTO mMaterial VALUES (44, '자바 예외 처리', 'https://www.tutorialspoint.com/java/java_exceptions.htm', '자바에서 예외 처리 및 오류 관리', 3, 3, '2024-01-22');
INSERT INTO mMaterial VALUES (45, '자바 컬렉션 프레임워크', 'https://www.geeksforgeeks.org/collections-in-java-2/', '자바 컬렉션 프레임워크의 활용법', 3, 3, '2024-01-22');
INSERT INTO mMaterial VALUES (46, 'C 메모리 동적 할당', 'https://www.geeksforgeeks.org/dynamic-memory-allocation-in-c/', 'C에서 동적 메모리 할당 기법', 3, 3, '2024-01-22');
INSERT INTO mMaterial VALUES (47, 'C 링커와 컴파일러', 'https://www.geeksforgeeks.org/compilation-process-in-c/', 'C 프로그램의 컴파일과 링킹 과정', 3, 3, '2024-01-22');
INSERT INTO mMaterial VALUES (48, 'C에서의 다차원 배열', 'https://www.geeksforgeeks.org/multidimensional-arrays-in-c/', 'C에서 다차원 배열을 처리하는 방법', 3, 3, '2024-01-22');
INSERT INTO mMaterial VALUES (49, 'C++ 프로그래밍 기본', 'https://www.learncpp.com/', 'C++ 언어의 기본 문법과 개념', 3, 3, '2024-01-22');
INSERT INTO mMaterial VALUES (50, 'C++ 객체지향 프로그래밍', 'https://www.learncpp.com/cpp-tutorial/object-oriented-programming/', 'C++에서 객체지향 프로그래밍의 개념', 3, 3, '2024-01-22');
INSERT INTO mMaterial VALUES (51, 'C++ 템플릿', 'https://www.learncpp.com/cpp-tutorial/templates/', 'C++에서 템플릿을 활용한 프로그래밍', 3, 3, '2024-01-22');
INSERT INTO mMaterial VALUES (52, 'C++ STL(표준 템플릿 라이브러리)', 'https://www.geeksforgeeks.org/the-c-standard-template-library-stl/', 'C++에서 STL 라이브러리 활용법', 3, 3, '2024-01-22');
INSERT INTO mMaterial VALUES (53, 'Python 프로그래밍 기초', 'https://www.python.org/about/gettingstarted/', 'Python의 기본 문법과 설치법', 7, 11, '2024-04-11');
INSERT INTO mMaterial VALUES (54, 'Python 데이터 구조', 'https://www.geeksforgeeks.org/python-data-structures/', 'Python에서 리스트, 튜플, 세트, 딕셔너리 사용법', 7, 11, '2024-04-11');
INSERT INTO mMaterial VALUES (55, 'Python 제너레이터', 'https://realpython.com/introduction-to-python-generators/', 'Python 제너레이터 사용법', 7, 11, '2024-04-11');
INSERT INTO mMaterial VALUES (56, 'Python 함수형 프로그래밍', 'https://realpython.com/python-functional-programming/', 'Python에서 함수형 프로그래밍 기법', 7, 11, '2024-04-11');
INSERT INTO mMaterial VALUES (57, 'Python 객체지향 프로그래밍', 'https://www.geeksforgeeks.org/python-object-oriented-programming/', 'Python에서 객체지향 프로그래밍 기법', 7, 11, '2024-04-11');
INSERT INTO mMaterial VALUES (58, 'Django 기본 개념', 'https://www.djangoproject.com/start/', 'Django 프레임워크의 기본 개념과 사용법', 4, 4, '2024-02-11');
INSERT INTO mMaterial VALUES (59, 'Django 모델(Model)과 데이터베이스', 'https://docs.djangoproject.com/en/stable/topics/db/models/', 'Django에서 모델과 데이터베이스 연결', 4, 4, '2024-02-11');
INSERT INTO mMaterial VALUES (60, 'Django 템플릿 시스템', 'https://docs.djangoproject.com/en/stable/topics/templates/', 'Django 템플릿을 활용한 HTML 렌더링', 4, 4, '2024-02-11');
INSERT INTO mMaterial VALUES (61, 'Django 관리자(Admin) 설정', 'https://docs.djangoproject.com/en/stable/ref/contrib/admin/', 'Django 관리자 사이트 설정 및 활용법', 4, 4, '2024-02-11');
INSERT INTO mMaterial VALUES (62, 'Django의 인증 시스템', 'https://docs.djangoproject.com/en/stable/topics/auth/', 'Django 인증 시스템 구현 및 사용법', 4, 4, '2024-02-11');
INSERT INTO mMaterial VALUES (63, 'MySQL 기본 개념', 'https://dev.mysql.com/doc/refman/8.0/en/', 'MySQL의 기본 개념과 설치법', 6, 10, '2024-04-01');
INSERT INTO mMaterial VALUES (64, 'MySQL 데이터베이스 생성 및 관리', 'https://www.digitalocean.com/community/tutorials/how-to-create-and-use-a-database-in-mysql', 'MySQL에서 데이터베이스 생성 및 관리 방법', 6, 10, '2024-04-01');
INSERT INTO mMaterial VALUES (65, 'MySQL 테이블 및 쿼리', 'https://www.w3schools.com/mysql/', 'MySQL에서 테이블 생성 및 기본적인 SQL 쿼리', 6, 10, '2024-04-01');
INSERT INTO mMaterial VALUES (66, 'MySQL 조인(JOIN) 사용법', 'https://www.geeksforgeeks.org/sql-join/', 'MySQL에서 다양한 조인 종류와 사용법', 6, 10, '2024-04-01');
INSERT INTO mMaterial VALUES (67, 'MySQL 인덱스(Index) 활용', 'https://www.geeksforgeeks.org/indexes-in-mysql/', 'MySQL에서 인덱스를 활용하여 성능 최적화하기', 6, 10, '2024-04-01');
INSERT INTO mMaterial VALUES (68, 'Node.js 개요', 'https://nodejs.org/en/docs/', 'Node.js의 기본 개념과 설치법', 5, 5, '2024-05-01');
INSERT INTO mMaterial VALUES (69, 'Node.js 비동기 프로그래밍', 'https://www.geeksforgeeks.org/node-js-asynchronous-programming/', 'Node.js에서 비동기 프로그래밍 기법과 이벤트 루프 활용법', 5, 5, '2024-05-01');
INSERT INTO mMaterial VALUES (70, 'Node.js와 Express.js 사용법', 'https://expressjs.com/en/starter/installing.html', 'Node.js에서 Express.js를 사용하여 웹 서버 구축하는 방법', 5, 5, '2024-05-01');
INSERT INTO mMaterial VALUES (71, '딥러닝 개요', 'https://www.tensorflow.org/tutorials', '딥러닝의 기본 개념과 TensorFlow 활용법', 7, 2, '2024-06-01');
INSERT INTO mMaterial VALUES (72, '인공지능을 위한 딥러닝 기초', 'https://www.coursera.org/learn/intro-to-tensorflow', '딥러닝을 위한 TensorFlow와 Keras 기초', 7, 2, '2024-06-01');
INSERT INTO mMaterial VALUES (73, '신경망 구조 및 학습', 'https://www.geeksforgeeks.org/deep-neural-networks-using-keras/', '딥러닝에서의 신경망 구조 설계 및 학습법', 7, 2, '2024-06-01');
INSERT INTO mMaterial VALUES (74, '딥러닝 모델 평가', 'https://towardsdatascience.com/understanding-evaluation-metrics-for-deep-learning-289212c157fa', '딥러닝 모델 성능 평가 지표와 기법', 7, 2, '2024-06-01');
INSERT INTO mMaterial VALUES (75, 'JSP 기본 개념', 'https://www.javatpoint.com/jsp-tutorial', 'JSP의 기본 개념과 구조', 8, 1, '2024-05-07');
INSERT INTO mMaterial VALUES (76, 'JSP 페이지 작성 및 실행', 'https://www.tutorialspoint.com/jsp/jsp_first_application.htm', 'JSP 페이지 작성과 실행 방법', 8, 1, '2024-05-07');
INSERT INTO mMaterial VALUES (77, 'JSP와 데이터베이스 연동', 'https://www.journaldev.com/1314/jsp-servlet-database-connection', 'JSP와 MySQL을 연결하여 데이터베이스 연동하는 방법', 8, 1, '2024-05-07');
INSERT INTO mMaterial VALUES (78, 'JSP에서 세션 관리', 'https://www.geeksforgeeks.org/sessions-in-jsp/', 'JSP에서 세션을 관리하는 방법', 8, 1, '2024-05-07');
INSERT INTO mMaterial VALUES (79, 'MongoDB 기본 개념', 'https://www.geeksforgeeks.org/mongodb-introduction/', 'MongoDB의 기본 개념에 대해 배우기', 9, 6, '2024-05-10');
INSERT INTO mMaterial VALUES (80, 'MongoDB에서 데이터 모델링', 'https://www.mongodb.com/blog/post/understanding-mongodb-data-modeling', 'MongoDB에서 효과적인 데이터 모델링 방법에 대해 배우기', 9, 6, '2024-05-12');

select * from mmaterial;